# Generated by Django 2.2.4 on 2021-02-21 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hilo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='statusReport',
            new_name='Poll',
        ),
    ]
