# Generated by Django 2.2.4 on 2021-02-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hilo', '0005_comment_favorite_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='post',
        ),
    ]
