# Generated by Django 2.2.4 on 2021-02-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hilo', '0006_auto_20210226_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connections',
            field=models.ManyToManyField(blank=True, to='hilo.User'),
        ),
        migrations.CreateModel(
            name='Connection_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='hilo.User')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='hilo.User')),
            ],
        ),
    ]
