# Generated by Django 2.2.4 on 2021-02-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hilo', '0007_auto_20210226_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='https://bootdey.com/img/Content/avatar/avatar2.png', upload_to='static/uploads/'),
        ),
    ]
