# Generated by Django 2.2.4 on 2021-03-01 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hilo', '0012_auto_20210226_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection_request',
            old_name='created',
            new_name='created_at',
        ),
    ]
