# Generated by Django 2.2.4 on 2021-03-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hilo', '0013_auto_20210228_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection_request',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('D', 'Declined'), ('P', 'Pending')], default='none', max_length=1),
            preserve_default=False,
        ),
    ]
